import turtle
pam=turtle.Turtle()
pam.up()
pam.goto(-300,0)
pam.down()
pam.width(5)
pam.color('green')
pam.fd(100)
pam.color('red')
pam.fd(100)
pam.color('green')
pam.fd(100)
pam.color('red')
pam.fd(100)
pam.color('green')
pam.fd(100)
pam.color('red')
pam.fd(100)
